### ISSUE TITLE
Add isFixedPitch flag to OpenMono

### ISSUE THREAD

**Issue by musm** [kiwi0fruit/sugartex#3]
See discussion https://github.com/google/fonts/issues/225

I would greatly appreciate patching Open Mono with this flag, it greatly enhances the usability of this font for coding.

**Comment by kiwi0fruit** [comment]
Good idea! I use it only in Atom editor and browser so I don't really care for a flag. But I guess some programs would need the flag.

Could you elaborate on how to add this flag? Can it be set in FontForge?

**Comment by musm** [comment]
Maybe this is a good hint

https://sourceforge.net/p/fontforge/mailman/fontforge-users/thread/CALuKHAcevsOKk0WRk9HDTqUbEmfNw3sGNoyQCjdpDoaeqoJy5A%40mail.gmail.com/

> 
> Re: [Fontforge-users] Regenerated font does not recognize as a Monospace in WindowsFrom: Khaled Hosny <khaledhosny@eg...> - 2012-09-29 10:38:57
> --
> On Sat, Sep 29, 2012 at 11:52:33AM +0530, pravin.d.s@... wrote: > Hi, >  >   I have downloaded https://googlefontdirectory.googlecode.com/hg/ofl/cousine/  > Cousine-Regular.ttf and saved as .sfd and regenerated ttf from it. But > regenerated font does not get recognized as a Monospace in Windows http:// > http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html Putty.exe >   While the original downloaded font get recognized there properly. >  >   What might be going wrong while saving it as .sfd and regenerating .ttf? >  >   Regenerated font http://pravins.fedorapeople.org/Test-Cousine.ttf  The original font has the isFixedPitch bit in post table set which it seems used by some application to recognise monospace fonts (though this, arguably, is wrong, there is no requirement that all monnospace fonts set it). Per the spec, isFixedPitch is only set when all glyphs in the font have the same width, but the font has a zero width ".null" glyph, so FontForge does not set isFixedPitch when generating the font (which is the right thing to do, some applications is know to behave wrongly with such a font).  Removing that glyph (which seems to serve no purpose and was probably auto inserted by the tool generating the font), should do the trick.  Regards,  Khaled
> 
>

**Comment by kiwi0fruit** [comment]
> We have lots of Zero width characters in Cousine-Regular fonts and removing
them looks not good solution.

Strange, I guess I've seen some zero-width combining characters in Consolas but it's still has a flag...

**Comment by kiwi0fruit** [comment]
But removing glyphs seems to be the wrong way...

I'll check if the problem arises from me using monospacifyer the wrong way. If not then I guess it should be fixed there: additional option of something.

By the way: what applications do need this flag?

**Comment by kiwi0fruit** [comment]
But there's still an issue of combining characters : I would  prefer have them properly instead of setting this flag. So why I curious about  consolas (may be combining characters do not mess with  a flag).

**Comment by kiwi0fruit** [comment]
I have no motivation to do this. So I won't fix it. But I guess the simplest way is to try to apply monospacifier to all font styles even for regular one - and see if it would solve the issue (and won't introduce chars with broken height - I've seen such bugs after applying monospacifier).

**Comment by kiwi0fruit** [comment]
I could try re-build open mono after flag is set in Google fonts: https://github.com/google/fonts/pull/1824 Luckily the flag won't be changed by monospacifier.

**Comment by kiwi0fruit** [comment]
Closed in favor of https://github.com/kiwi0fruit/open-fonts/issues/3

**Comment by kiwi0fruit** [comment]
I wanted to try the simplest way of monospacifying all roboto mono styles but this would require testing if this breaks hinting on Windows. I don't want to test it. So I'll only wait for upstream fix.
